/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SS1.c
**     Project     : try2_codewarrior
**     Processor   : MC56F8006_48_LQFP
**     Component   : SynchroSlave
**     Version     : Component 02.252, Driver 02.04, CPU db: 3.00.209
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2018-08-12, 15:32, # CodeGen: 1
**     Abstract    :
**         This component "SynchroSlave" implements SLAVE part of synchronous
**         serial master-slave communication.
**     Settings    :
**         Synchro type                : SLAVE
**
**         Serial channel              : SPI
**
**         Protocol
**             Clock edge              : rising
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI_DRCV  [F102]
**             Output buffer           : SPI_DXMIT [F103]
**             Control register        : SPI_SCTRL [F100]
**             Mode register           : SPI_DSCTRL [F101]
**             Baud setting reg.       : SPI_SCTRL [F100]
**
**         Input interrupt
**             Vector name             : INT_SPI_Rx_Full_Over_ModeFault
**             Priority                : 0
**
**         Output interrupt
**             Vector name             : INT_SPI_Tx_Empty
**             Priority                : 0
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     24     |  GPIOB3_ANA3_ANB3_PWM5_MOSI_TIN3_CMP1_OUT
**               Output     |     25     |  GPIOB2_ANA2_ANB2_MISO_TIN2_CMP0_OUT
**               Clock      |     4      |  GPIOB5_FAULT3_SCLK_T1
**           Select slave   |     2      |  GPIOB1_ANA12_SSB_SDA_CMP2_P3
**         ----------------------------------------------------------
**     Contents    :
**         RecvChar        - byte SS1_RecvChar(SS1_TComData *Chr);
**         SendChar        - byte SS1_SendChar(SS1_TComData Chr);
**         GetCharsInRxBuf - word SS1_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word SS1_GetCharsInTxBuf(void);
**         GetError        - byte SS1_GetError(SS1_TError *Err);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SS1.c
** @version 02.04
** @brief
**         This component "SynchroSlave" implements SLAVE part of synchronous
**         serial master-slave communication.
*/         
/*!
**  @addtogroup SS1_module SS1 module documentation
**  @{
*/         

/* MODULE SS1. */

#include "Events.h"
#include "SS1.h"

#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define RUNINT_FROM_TX   0x20U         /* Interrupt is in progress */
#define FULL_RX          0x40U         /* Full receive buffer      */

static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Unused */
static byte ErrFlag;                   /* Error flags for GetError method */
static SS1_TComData BufferRead;        /* Input char SPI commmunication */
static SS1_TComData BufferWrite;       /* Output char SPI commmunication */

/*
** ===================================================================
**     Method      :  SS1_RecvChar (component SynchroSlave)
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**         [ Version specific information for Freescale 56800
**         derivatives ] 
**         DMA mode:
**         If DMA controller is available on selected CPU and receiver
**         is configured to use DMA controller then this method only
**         sets the selected DMA channel. Status of the DMA transfer
**         can then be checked using method GetCharsInRxBuf. See
**         typical usage for details about communication using DMA.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_OVERRUN - Overrun error is detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. 
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. This error
**                           does not need to be supported on some Cpu
**                           (see generated code).
** ===================================================================
*/
byte SS1_RecvChar(SS1_TComData *Chr)
{
  register byte FlagTmp;

  if ((SerFlag & CHAR_IN_RX) == 0x00U) { /* Is any char in the RX buffer? */
    return ERR_RXEMPTY;                /* If no then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  *Chr = BufferRead;                   /* Read the char */
  FlagTmp = SerFlag;                   /* Safe the flags */
  SerFlag &= (byte)~(OVERRUN_ERR | CHAR_IN_RX | FULL_RX); /* Clear flag "char in RX buffer" */
  ExitCritical();                      /* Enable global interrupts */
  if ((FlagTmp & OVERRUN_ERR) != 0U) { /* Is the overrun occured? */
    return ERR_OVERRUN;                /* If yes then return error */
  }
  else {
    return ERR_OK;
  }
}

/*
** ===================================================================
**     Method      :  SS1_SendChar (component SynchroSlave)
**     Description :
**         Sends one character to the channel.
**         [ Version specific information for Freescale 56800
**         derivatives ] 
**         DMA mode:
**         If DMA controller is available on the selected CPU and the
**         transmitter is configured to use DMA controller then this
**         method only sets the selected DMA channel. The status of the
**         DMA transfer can then be checked using GetCharsInTxBuf
**         method. See the typical usage for details about
**         communication using DMA.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_DISABLED -  Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte SS1_SendChar(SS1_TComData Chr)
{
  if ((SerFlag & FULL_TX) != 0x00U) {  /* Is any char in the TX buffer */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  BufferWrite = Chr;                   /* Store char to the temporary variable */
  SerFlag |= (FULL_TX);                /* Set the flag "full TX buffer" */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SS1_GetCharsInRxBuf (component SynchroSlave)
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**         [ Version specific information for Freescale 56800
**         derivatives ] 
**         DMA mode:
**         If DMA controller is available on the selected CPU and the
**         receiver is configured to use DMA controller then this
**         method returns the number of characters in the receive
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/
word SS1_GetCharsInRxBuf(void)
{
  return ((word)(((SerFlag & CHAR_IN_RX) != 0x00U) ? 1 : 0)); /* Return number of chars in receive buffer */
}

/*
** ===================================================================
**     Method      :  SS1_GetCharsInTxBuf (component SynchroSlave)
**     Description :
**         Returns the number of characters in the output buffer.
**         [ Version specific information for Freescale 56800
**         derivatives ] 
**         DMA mode:
**         If DMA controller is available on the selected CPU and the
**         transmitter is configured to use DMA controller then this
**         method returns the number of characters in the transmit
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/
word SS1_GetCharsInTxBuf(void)
{
  return ((word)(((SerFlag & FULL_TX) != 0x00U)?(word)1:(word)0)); /* Return number of chars in the transmit buffer */
}

/*
** ===================================================================
**     Method      :  SS1_GetError (component SynchroSlave)
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned in given methods). The component accumulates
**         errors in a set; after calling [GetError] this set is
**         returned and cleared. This method is available only if the
**         "Interrupt service/event" property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - A pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte SS1_GetError(SS1_TError *Err)
{
  EnterCritical();                     /* Disable global interrupts */
  Err->err = 0U;
  Err->errName.OverRun = (((ErrFlag & OVERRUN_ERR) != 0U) ? 1U:0U); /* Overrun error */
  ErrFlag = 0x00U;                     /* Reset error flags */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SS1_InterruptRx (component SynchroSlave)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR       0x01U
#define ON_FULL_RX     0x02U
#define ON_RX_CHAR     0x04U
#define ON_FREE_TX     0x08U
#define ON_TX_CHAR     0x10U
#define ON_EMPTY_CHAR  0x20U
#define ON_RX_CHAR_EXT 0x40U
#pragma interrupt alignsp saveall
void SS1_InterruptRx(void)
{
  register word Data;                  /* Temporary variable for data */
  register byte Flags = 0U;            /* Temporary variable for flags */
  register word Status;                /* Temporary variable for flags */

  Status = getReg(SPI_SCTRL);          /* Read the device error register */
  Data = getReg(SPI_DRCV);             /* Read data from receiver */
  if (getRegBit(SPI_SCTRL,OVRF)) {     /* Occured any overflow condition between SPI_SCTRL and SPI_DRCV reading? */
    getReg(SPI_DRCV);                  /* Clear the overflow flag */
    Status |= SPI_SCTRL_OVRF_MASK;     /* Set overrun flag */
  }
  if (Status & SPI_SCTRL_OVRF_MASK) {  /* Occured any overflow condition? */
    SerFlag |= (OVERRUN_ERR);          /* Set the OnError flag */
    ErrFlag |= (OVERRUN_ERR);          /* If yes then set the Error flag for GetError method */
    Flags |= (ON_ERROR);               /* If yes then set the OnError flag */
  }
  if ((SerFlag & CHAR_IN_RX) != 0x00U) { /* Is the overrun error flag set? */
    SerFlag |= (OVERRUN_ERR);          /* If yes then set the OnError flag */
    ErrFlag |= (OVERRUN_ERR);          /* If yes then set the Error flag for GetError method */
    Flags |= (ON_ERROR);               /* If yes then set the OnError flag */
  }
  SerFlag |= (CHAR_IN_RX);             /* Set flag "char in RX buffer" */
  BufferRead = (SS1_TComData)Data;     /* Read data from receiver */
  if ((SerFlag & FULL_TX) != 0x00U) {  /* Is "Full TX buffer" flag set? */
    setReg(SPI_DXMIT,BufferWrite);     /* If yes then store char to the transmit register */
    Flags |= (ON_TX_CHAR);             /* Set the OnTxChar flag */
    SerFlag &= (byte)~(FULL_TX);       /* Reset flag "Full TX buffer" */
  }
  else {
    setReg(SPI_DXMIT,SS1_EOF);         /* If no then store the empty char to the transmit register */
    Flags |= ON_EMPTY_CHAR;            /* Set the OnTxEmptyChar flag */
  }
  if (Flags & ON_ERROR) {              /* Is any error flag set? */
    SS1_OnError();                     /* Invoke user event */
  }
  else {
    SS1_OnRxChar();                    /* Invoke user event */
  }
  if (Flags & ON_TX_CHAR) {            /* Is OnTxChar flag set? */
    SS1_OnTxChar();                    /* Invoke user event */
  }
  if (Flags & ON_EMPTY_CHAR) {         /* Is OnFreeTxBuf flag set? */
    SS1_OnTxEmptyChar();               /* Invoke user event */
  }
}

/*
** ===================================================================
**     Method      :  SS1_Init (component SynchroSlave)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SS1_Init(void)
{
  /* SPI_SCTRL: SPR=0,DSO=1,ERRIE=0,MODFEN=0,SPRIE=0,SPMSTR=0,CPOL=0,CPHA=1,SPE=0,SPTIE=0,SPRF=0,OVRF=0,MODF=1,SPTE=0 */
  setReg(SPI_SCTRL,0x1042);            /* Set control register */
  /* SPI_DSCTRL: WOM=0,??=0,??=0,BD2X=0,SSB_IN=0,SSB_DATA=0,SSB_ODM=0,SSB_AUTO=0,SSB_DDR=0,SSB_STRB=0,SSB_OVER=0,SPR3=0,DS=7 */
  setReg(SPI_DSCTRL,0x07);             /* Set data size and control register */
  SerFlag = 0U;                        /* Reset all flags */
  ErrFlag = 0U;                        /* Reset all flags in mirror */
  setRegBit(SPI_SCTRL,SPE);            /* Enable device */
  setReg(SPI_DXMIT,SS1_EOF);           /* Store the empty char to the transmit register */
  setRegBits(SPI_SCTRL,(SPI_SCTRL_ERRIE_MASK|SPI_SCTRL_SPRIE_MASK)); /* Enable receive and error interrupts */
}

/* END SS1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
